services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.development
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST: database
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
    depends_on:
      - database
    command: ["yarn", "run", "start:dev"]
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - .env.development
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}